session Stark_Core in "Core" = Berlekamp_Zassenhaus +
  options [document = false]
theories [document = true]
    Stark

session Stark_Completeness in "Completeness" = Stark_Core +
  options [document = false]
theories [document = true]
    Completeness

session Stark_Examples in "Examples" = Stark_Core +
  options [document = false]
theories [document = true]
    Square_Sequence
    Prime_Field_Bridge
    Square_Sequence_Workload
    Prime_192_Replay
    Prime_192_Certificate
    Prime_Field_192

session Stark in "Soundness" = Stark_Core +
  options [document = pdf, document_output = "../output"]
  sessions
    Stark_Completeness
    Stark_Examples
  (* Import the retained example for the combined proof document. *)
  theories [document = true]
    Stark_Examples.Square_Sequence
  theories
    Staged_Security_Experiment_RO_Budgets
    Staged_Security_Experiment_RO_Transcript_Budgets
    Staged_Security_Experiment_RO_Transcript_Collision_Budgets
    Staged_Security_Experiment_RO_Checked
    FS_Adversary_Model
    FS_Staged_Allowance_Audit
    FS_Fixed_Randomness_Replay
    FS_Private_Randomness_Normalization
    FS_Transcript_Prescan
    FS_Query_Round_Prescan
    FS_Query_Phase_Scan
    FS_Query_Phase_Prescan
    FS_Header_Coupling
    FS_Guarded_Header_Reconstruction
    FS_Full_Reconstruction_Primitives
    FS_Full_Transcript_Reconstruction
    FS_Staged_Replay_Composition
    FS_Adaptive_Staged_Embedding
    FS_Replay_Allowance
    FS_Builder_Accounting
    FS_Builder_Witness_Accounting
    Soundness_RO_Drift_Per_Key
    FS_Challenge_Accounting
    FS_Alpha_Accounting
    FS_Replay_Soundness
    FS_Probability_Accounting
    FS_Compiled_Event_Accounting
    FS_Residual_Accounting
    FS_Accounted_Soundness
    FS_Refined_Soundness
    FS_Prefix_Witness_Replay
    FS_Prefix_Target_Accounting
    FS_Prefix_Soundness
    FS_First_Root_Accounting
    FS_First_Root_Alpha
    FS_First_Root_Soundness
    FS_Square_First_Root_Ledger
    FS_Square_First_Root_Comparison
    FS_Square_Replay_Soundness
    FS_Square_Accounted_Ledger
    FS_Square_Refined_Ledger
    FS_Square_135_Arithmetic
    FS_Square_192_135
    FS_Square_Prefix_Ledger
    FS_Square_137_Arithmetic
    FS_Square_192_137
    Publication_Manifest
    Staged_Security_Experiment_RO_Verifier_Budgets
    Staged_Security_Experiment_RO_Checked_Replay
    Staged_Security_Experiment_RO_Query_State_Bridge
    Staged_Security_Experiment_RO_Query_Synchronization
    Staged_Security_Experiment_RO_Query_Round_Replay
    Staged_Security_Experiment_RO_Query_Rounds_Replay
    Staged_Security_Experiment_RO_Verify_Header_Replay
    Staged_Security_Experiment_RO_Event_Bridge
    Staged_Security_Experiment_RO_Query_List_Event
    Staged_Security_Experiment_RO_Query_List_Prequery
    Staged_Security_Experiment_RO_Query_List_Actual_Product
    Staged_Security_Experiment_RO_Query_List_Transcript_Product
    Staged_Security_Experiment_RO_Query_List_Actual_Path
    Controlled_RO_State_Relation
    Staged_Security_Experiment_RO_Adaptive_State_Relation
    Staged_Security_Experiment_RO_Transcript_Adaptive_State_Relation
    Soundness_FRI_First_Root_RO_Actual_Query_Product
    Soundness_FRI_First_Root_RO_Query_Phase_Prequery
    Soundness_FRI_First_Root_RO_State_Relation
    Soundness_FRI_First_Root_RO_Bounded_State_Relation
    Soundness_FRI_First_Root_RO_Adaptive_Query_Budget
    Soundness_FRI_First_Root_RO_Prequery_Bridge
    Soundness_FRI_First_Root_RO_Prequery_Bound
    Soundness_FRI_First_Root_RO_Prefix_Target_Bound
    Soundness_FRI_First_Root_RO_Prequery_Closed_Bound
    Soundness_FRI_First_Root_RO_Security_Query_Bound
    Soundness_FRI_First_Root_RO_Authenticated_Openings
    Soundness_FRI_First_Root_RO_Actual_Agreement
    Soundness_FRI_First_Root_RO_Verifier_Query_Boundary
    Soundness_FRI_First_Root_RO_Actual_Query_Classification
    Soundness_FRI_First_Root_RO_Actual_Query_Route
    Soundness_FRI_RO_Actual_Query_Partial_Evidence
    Soundness_FRI_RO_Actual_Query_Accepted_Evidence
    Soundness_FRI_RO_Actual_Query_Fold_Evidence
    Soundness_FRI_RO_Actual_Query_Chain_Conflict_Collapse
    Soundness_FRI_RO_Actual_Query_Joint_Evidence
    Soundness_FRI_RO_Actual_Query_Obstruction_Reduction
    Soundness_FRI_RO_Actual_Query_Obstruction_Events
    Soundness_FRI_RO_Actual_Query_Obstruction_Bounds
    Soundness_FRI_RO_Actual_Query_Obstruction_Collapse
    Soundness_FRI_RO_Actual_Query_Trace_Candidate
    Soundness_FRI_RO_Actual_Query_Composition_Candidate
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Boundary
    Soundness_FRI_Padded_Degree
    Soundness_FRI_Polynomial_Fold_Bounds
    Soundness_FRI_Conditioned_Interface
    Soundness_FRI_Conditioned_Multiround
    Soundness_FRI_Robust_Code_Distance
    Soundness_FRI_Robust_RS_List
    Soundness_FRI_Robust_Incidence
    Soundness_FRI_Robust_One_Round_Algebra
    Soundness_FRI_Robust_One_Round
    Soundness_FRI_Binary_Correlated_Agreement
    Soundness_FRI_Robust_Multiround
    Soundness_FRI_Robust_Exact_Rate_Multiround
    Soundness_FRI_Robust_Balanced_Schedule
    Soundness_FRI_Robust_Conceptual_Split
    Soundness_FRI_Robust_Exact_Rate_Conceptual_Split
    Soundness_FRI_Robust_Balanced_Conceptual_Split
    Soundness_FRI_Robust_Actual_Query
    Soundness_FRI_Robust_Balanced_Actual_Query
    Soundness_FRI_Robust_Query_Phase_Transport
    Soundness_FRI_Robust_Balanced_Query_Phase_Transport
    Soundness_FRI_Robust_Challenge_Relation
    Soundness_FRI_Robust_Exact_Rate_Challenge_Relation
    Soundness_FRI_Robust_Balanced_Challenge_Relation_Base
    Soundness_FRI_Robust_Balanced_Challenge_Relation
    Soundness_FRI_Robust_Decoded_Semantics
    Soundness_FRI_Robust_Decoded_Alpha_Pivot
    Soundness_FRI_Robust_Decoded_Rectangle
    Soundness_FRI_Robust_Balanced_Decoded_Rectangle
    Soundness_FRI_Robust_Trace_Classification
    Soundness_FRI_Robust_Exact_Rate_Trace_Classification
    Soundness_FRI_Robust_Balanced_Trace_Classification
    Soundness_FRI_Robust_Composition_Classification
    Soundness_FRI_Robust_Exact_Rate_Composition_Classification
    Soundness_FRI_Robust_Balanced_Composition_Classification
    Soundness_FRI_Robust_Security_Classification
    Soundness_FRI_Robust_Exact_Rate_Security_Classification
    Soundness_FRI_Robust_Balanced_Security_Classification
    Soundness_FRI_Robust_Parameter_Bound
    Soundness_FRI_Robust_Exact_Rate_Parameter_Bound
    Soundness_FRI_Robust_Balanced_Parameter_Bound
    Soundness_FRI_Robust_Balanced_Selected_Residual
    Soundness_FRI_Robust_Schedule_Optimality
    Soundness_FRI_Authenticated_Global_Chain_Audit
    Soundness_FRI_Correlated_Agreement_Fold
    Soundness_FRI_Correlated_Agreement_Query_Support
    Soundness_FRI_Correlated_Agreement_Residual_Bridge
    Soundness_FRI_Correlated_Agreement_Parameter_Gate
    Soundness_FRI_Correlated_Agreement_Challenge_Relations
    Soundness_FRI_Correlated_Agreement_Challenge_Fibers
    Soundness_FRI_Correlated_Agreement_Challenge_Outcomes
    Soundness_FRI_Correlated_Agreement_Adaptive_Charging
    Soundness_FRI_Correlated_Agreement_Guarded_Rectangles
    Soundness_FRI_Correlated_Agreement_Accepted_Chains
    Soundness_FRI_Correlated_Agreement_Actual_Query
    Soundness_FRI_Correlated_Agreement_Security_Classification
    Soundness_FRI_Query_Head_Range
    Soundness_FRI_Prefix_Local_Target_Bounds
    Soundness_FRI_Correlated_Agreement_Parameter_Bound
    Soundness_FRI_Correlated_Agreement_Comparison
    Soundness_FRI_Weighted_Semantic_Recovery
    Soundness_FRI_Weighted_Query_Routing
    Soundness_FRI_Weighted_Finite_Candidates
    Soundness_FRI_Weighted_Adaptive_Families
    Soundness_FRI_Weighted_Program_Logging
    Soundness_FRI_Weighted_Staged_Logging
    Soundness_FRI_Weighted_Verifier_Logging
    Soundness_FRI_Weighted_Execution_Replay
    Soundness_FRI_Weighted_Long_Paths
    Soundness_FRI_Weighted_Semantic_Portfolio
    Soundness_FRI_Weighted_Semantic_Endpoint
    Soundness_FRI_Weighted_Challenge_Completion
    Soundness_FRI_Weighted_Challenge_Portfolio
    Soundness_FRI_Weighted_FRI_Endpoint
    Soundness_FRI_Weighted_Residual_Union
    Soundness_FRI_Weighted_Soundness
    Soundness_FRI_Authenticated_Residual_Realization_Audit
    Soundness_FRI_Robust_Balanced_Selected_Actual_Query
    Soundness_FRI_Robust_Balanced_Selected_Query_Phase_Transport
    Soundness_FRI_Robust_Balanced_Strict_Selected_Residual
    Soundness_FRI_Robust_Balanced_Strict_Selected_Actual_Query
    Soundness_FRI_Robust_Balanced_Strict_Selected_Query_Phase_Transport
    Soundness_FRI_Robust_Balanced_Strict_Selected_Trace_Classification
    Soundness_FRI_Robust_Balanced_Strict_Selected_Composition_Classification
    Soundness_FRI_Robust_Balanced_Strict_Selected_Security_Classification
    Soundness_FRI_Robust_Balanced_Strict_Selected_Parameter_Bound
    Soundness_FRI_Conditioned_Conceptual_Split
    Soundness_FRI_Conditioned_Authenticated_Bridge
    Soundness_FRI_Conditioned_Query_Fiber
    Soundness_FRI_Conditioned_Prequery
    Soundness_FRI_Conditioned_RO_Prequery
    Soundness_FRI_Conditioned_RO_Verifier
    Soundness_FRI_Conditioned_RO_Security
    Soundness_FRI_Conditioned_Actual_Bridge
    Soundness_FRI_Conditioned_Challenge_Relation
    Soundness_FRI_Conditioned_Challenge_Outcome_Bridge
    Soundness_FRI_Conditioned_Security_Bridge
    Soundness_FRI_Conditioned_Security_Target_Bound
    Soundness_FRI_Conditioned_Builder_Split
    Soundness_FRI_Conditioned_Quantitative_Split
    Soundness_FRI_Conditioned_Query_Head
    Soundness_FRI_Conditioned_Query_Start
    Soundness_FRI_Conditioned_Query_Challenge_Dual
    Soundness_FRI_Conditioned_Prequery_Header
    Soundness_FRI_Conditioned_Prequery_Dual_Relation
    Soundness_FRI_Conditioned_Prequery_Drift_Base
    Soundness_FRI_Conditioned_Prequery_Challenge_Fibers
    Soundness_FRI_Conditioned_Prequery_Challenge_Activation
    Soundness_FRI_Conditioned_Prequery_Drift_Bound
    Soundness_FRI_Conditioned_Prequery_Transition_Bound
    Soundness_FRI_Conditioned_Prequery_Outcome_Bridge
    Soundness_Query_Agreement_Generalized
    Soundness_FRI_Conditioned_Composition_Padding_Agreement
    Soundness_FRI_Conditioned_Composition_Padding_Relation
    Soundness_FRI_Conditioned_Composition_Outcome_Bridge
    Soundness_FRI_Conditioned_Trace_Composition_Padding_Agreement
    Soundness_FRI_Conditioned_Trace_Composition_Padding_Relation
    Soundness_FRI_Conditioned_Trace_Composition_Padding_Outcome_Bridge
    Soundness_FRI_Conditioned_Explicit_Security_Events
    Soundness_FRI_Conditioned_Explicit_Security_Classification
    Soundness_FRI_RO_Query_Head_Dependent_Product
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Query_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_State_Relation
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Adaptive_Query_Budget
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Prequery_Closed_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Security_Query_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Obstruction_Classification
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Target_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Sampled_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Exact
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_Fiber
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_State_Relation
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_Adaptive_Query_Budget
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_Outcome_Bridge
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_Closed_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_Security_Bound
    Soundness_FRI_RO_Actual_Query_Trace_Composition_Alpha_Pivot_Parameter_Bound
    Soundness_FRI_Conditioned_Explicit_Parameter_Bound
    Soundness_FRI_RO_Actual_Query_Zero_Round_Prefix
    Soundness_FRI_RO_Actual_Query_Zero_Round_Query_Classification
    Soundness_FRI_RO_Actual_Query_Zero_Round_State_Relation
    Soundness_FRI_RO_Actual_Query_Zero_Round_Prefix_Target_Bound
    Soundness_FRI_RO_Actual_Query_Zero_Round_Prequery_Bound
    Soundness_FRI_RO_Actual_Query_Zero_Round_Security_Classification
    Soundness_FRI_RO_Actual_Query_Zero_Round_Composition_Classification
    Soundness_FRI_Conditioned_Zero_Round_Outcome_Bridge
    Soundness_FRI_Conditioned_Zero_Round_Security
    Soundness_FRI_RO_Actual_Query_Zero_Round_Composition_Query_Bound
    Soundness_FRI_RO_Actual_Query_Zero_Round_Alpha_Pivot_Bound
    Soundness_FRI_RO_Actual_Query_Zero_Round_Parameter_Bound
    Soundness_FRI_Conditioned_Explicit_Zero_Round_Parameter_Bound
    Soundness_FRI_Conditioned_Explicit_All_Rounds_Bound
    Soundness_FRI_Conditioned_Explicit_Nontriviality
    Soundness_FRI_Conditioned_Explicit_Arithmetic_Feasibility
    Soundness_FRI_Conditioned_Explicit_Component_Audit
    Soundness_FRI_Conditioned_Explicit_Residual_Projection_Obstruction
    Soundness_FRI_Conditioned_Explicit_Security_Target
    Soundness_FRI_Query_Future_Fresh_Zero_Budget
    Soundness_FRI_Query_Future_Count
    Staged_Security_Experiment_RO_Query_List_Future_Count_Product
    Staged_Security_Experiment_RO_Query_List_Future_Count_Exact_Product
    Staged_Security_Experiment_RO_Query_Rectangle_Family_Future_Count
    Soundness_FRI_Query_Head_Future_Count_Bound
    Soundness_FRI_Query_Head_Adaptive_Actual_Product
    Soundness_FRI_Query_Head_Adaptive_Rectangle_Family
    Soundness_FRI_Conditioned_Explicit_Complete_List_Adaptive_Products
    Soundness_FRI_Conditioned_Explicit_Complete_List_Adaptive_Parameter_Bound
    Soundness_FRI_Conditioned_Residual_Adaptive_Rectangle_Layers
    Soundness_FRI_Conditioned_Residual_Adaptive_Rectangle_Products
    Soundness_FRI_Conditioned_Explicit_Adaptive_Rectangles
    Soundness_FRI_Conditioned_Explicit_Adaptive_Rectangle_Security
    Soundness_FRI_Conditioned_Explicit_Adaptive_Rectangle_Parameter_Bound
    Soundness_FRI_Conditioned_Explicit_Residual_Actual_Product_Zero
    Soundness_FRI_Conditioned_Explicit_Residual_Complete_List_Classification
    Soundness_FRI_Conditioned_Explicit_Residual_Query_Phase_Target
    Soundness_FRI_Conditioned_Explicit_Complete_List_Padding_Zero
    Soundness_FRI_Conditioned_Explicit_Complete_List_Security_Classification
    Soundness_FRI_Conditioned_Explicit_Complete_List_Good_Query_Zero
    Soundness_FRI_Conditioned_Explicit_Complete_List_Parameter_Bound
    Soundness
    Soundness_Square_Sequence_Workload
    Soundness_Square_Sequence_192
    Square_Sequence_Interpolation
    Square_Sequence_192_Core_Completeness
    RO_Honest_Replay_Primitives
    RO_Honest_Trace_Reconstruction
    RO_Honest_Header_Reconstruction
    RO_Honest_Composition_Reconstruction
    Square_Sequence_192_RO_Header
    Square_Sequence_192_RO_Composition
    RO_Honest_Query_Reconstruction
    RO_Honest_Opening_Chunks
    Square_Sequence_192_RO_Openings
    RO_Honest_Verifier_Replay
    RO_Honest_Verifier_Openings
    Square_Sequence_192_RO_FRI_Algebra
    RO_Honest_Verifier_FRI_Chains
    Square_Sequence_192_RO_FRI_Verifier
    Square_Sequence_192_RO_Query_Values
    Square_Sequence_192_RO_Query_Witnesses
    Square_Sequence_192_RO_Query_Verifier
    RO_Honest_Verifier_Header_Primitives
    RO_Honest_Verifier_Header
    Square_Sequence_192_RO_Verifier_Header
    RO_Honest_Verifier_Query_Replay
    Square_Sequence_192_RO_Completeness
    Soundness_Square_Budget_Counts
    Soundness_Square_Prefix_Budgets
    Soundness_Square_Weighted_Ledger
    Soundness_Square_Allocation_Arithmetic
    Soundness_Square_Allocation_Bound
    Soundness_Square_Uniform_Soundness
    Soundness_Square_128_Arithmetic
    Soundness_Square_128_Target
    Soundness_Square_192_128
  document_theories
    Stark_Core.NNReal
    Stark_Core.Prob_Dist
    Stark_Core.Hash_Monad
    Stark_Core.Channel_Core
    Stark_Core.Channel_Transcript
    Stark_Core.Channel_Instances
    Stark_Core.Channel
    Stark_Core.Galois_Field_5
    Stark_Core.Merkle_Tree
    Stark_Core.Prob_Monad
    Stark_Core.Stark
    Stark_Completeness.Completeness_Core
    Stark_Completeness.Completeness_Algebra
    Stark_Completeness.Completeness_Transcript
    Stark_Completeness.Completeness_Replay
    Stark_Completeness.Completeness_Query
    Stark_Completeness.Completeness_FRI
    Stark_Completeness.Completeness_Verifier
    Stark_Completeness.Completeness
    Stark_Examples.Square_Sequence
    Stark_Examples.Prime_Field_Bridge
    Stark_Examples.Square_Sequence_Workload
    Stark_Examples.Prime_192_Replay
    Stark_Examples.Prime_192_Certificate
    Stark_Examples.Prime_Field_192
  document_files
    "root.tex"
